server:
  port: 8098    #default port where the service will be started
 
eureka:         #tells about the Eureka server details and its refresh time
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5
 
spring:     
  application:
    name: order-service   #current service name to be used by the eureka server
  datasource:
    url: jdbc:mysql://localhost:3306/orderdb
    username: pranaya
    password: pranay@123
  jpa:
    properties:
      hibernate:
         dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
     
management:
  security:
    enabled: false  #disable the spring security on the management endpoints like /env, /refresh etc. 
 
restaurant:
  search:
    item:
      url: http://localhost:8080/item/id/
